ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_UAMS_ACCOUNT_MAPPING"
    ADD CONSTRAINT "ACTMAP_UUID" UNIQUE ("ACTMAP_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_UAMS_APP_LOG"
    ADD CONSTRAINT "APPLG_UUID" UNIQUE ("APPLG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_EXTSVC_ORGCFGMETA"
    ADD CONSTRAINT "CEOCM_UUID" UNIQUE ("CEOCM_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_EXTSVC_ORGCONFIG"
    ADD CONSTRAINT "CEOC_UUID" UNIQUE ("CEOC_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_FORM_FIELD"
    ADD CONSTRAINT "CFFMF_UUID" UNIQUE ("CFFMF_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_FNT_BTN"
    ADD CONSTRAINT "CFFNB_UUID" UNIQUE ("CFFNB_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_FORM"
    ADD CONSTRAINT "CFFRM_NAME" UNIQUE ("CFFRM_NAME", "CFFRM_VERSION");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_FORM"
    ADD CONSTRAINT "CFFRM_UUID" UNIQUE ("CFFRM_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_MODEL_FIELD"
    ADD CONSTRAINT "CFMDF_UUID" UNIQUE ("CFMDF_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_MODEL"
    ADD CONSTRAINT "CFMOD_CODE" UNIQUE ("CFMOD_CODE", "CFMOD_VERSION");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_MODEL"
    ADD CONSTRAINT "CFMOD_UUID" UNIQUE ("CFMOD_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_TABLE"
    ADD CONSTRAINT "CFTAB_NAME" UNIQUE ("CFTAB_NAME");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_TABLE"
    ADD CONSTRAINT "CFTAB_UUID" UNIQUE ("CFTAB_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FLEX_TABLE_COL"
    ADD CONSTRAINT "CFTBC_UUID" UNIQUE ("CFTBC_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_META_COLUMN"
    ADD CONSTRAINT "CMCMD_CMTMD_UUID" UNIQUE ("CMCMD_CMTMD_UUID", "CMCMD_COLUMN_NAME");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_META_COLUMN"
    ADD CONSTRAINT "CMCMD_UUID" UNIQUE ("CMCMD_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_META_DATA_SOURCE"
    ADD CONSTRAINT "CMSRC_NAME" UNIQUE ("CMSRC_NAME");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_META_DATA_SOURCE"
    ADD CONSTRAINT "CMSRC_UUID" UNIQUE ("CMSRC_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_DASVC_SERVICE"
    ADD CONSTRAINT "CMSVC_CODE" UNIQUE ("CMSVC_CODE");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_DASVC_SERVICE"
    ADD CONSTRAINT "CMSVC_UUID" UNIQUE ("CMSVC_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_META_MODEL"
    ADD CONSTRAINT "CMTMD_SOURCE_UUID" UNIQUE ("CMTMD_SOURCE_UUID", "CMTMD_TABLE_NAME");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_META_MODEL"
    ADD CONSTRAINT "CMTMD_UUID" UNIQUE ("CMTMD_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_NOTICE"
    ADD CONSTRAINT "CN_UUID_UNIQUE" UNIQUE ("CN_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_ACCOUNT"
    ADD CONSTRAINT "CRACT_CODE" UNIQUE ("CRACT_CODE");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_ACCOUNT_RELATION"
    ADD CONSTRAINT "CRACT_UUID" UNIQUE ("CRACT_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_CONFIG"
    ADD CONSTRAINT "CRCFG_UUID" UNIQUE ("CRCFG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_DICT"
    ADD CONSTRAINT "CRDCT_UUID" UNIQUE ("CRDCT_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_OAUTH_CREDENTIALS"
    ADD CONSTRAINT "CREDT_UUID" UNIQUE ("CREDT_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_RESRC_FILE"
    ADD CONSTRAINT "CRFILE_UUID" UNIQUE ("CRFILE_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FUNCTION"
    ADD CONSTRAINT "CRFNT_CODE" UNIQUE ("CRFNT_CODE");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_FUNCTION"
    ADD CONSTRAINT "CRFNT_UUID" UNIQUE ("CRFNT_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_GROUP"
    ADD CONSTRAINT "CRGRP_UUID" UNIQUE ("CRGRP_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_LOG"
    ADD CONSTRAINT "CRLOG_UUID" UNIQUE ("CRLOG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_MENU"
    ADD CONSTRAINT "CRMNU_INDEX_KEY" UNIQUE ("CRMNU_INDEX_KEY");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_MENU"
    ADD CONSTRAINT "CRMNU_UUID" UNIQUE ("CRMNU_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_NUMBER_CONFIG"
    ADD CONSTRAINT "CRNOC_CODE" UNIQUE ("CRNOC_CODE");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_NUMBER_CONFIG"
    ADD CONSTRAINT "CRNOC_UUID" UNIQUE ("CRNOC_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_NUMBER_HISTORY"
    ADD CONSTRAINT "CRNOH_UUID" UNIQUE ("CRNOH_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_ORG_TREE"
    ADD CONSTRAINT "CROAT_REF_UUID" UNIQUE ("CROAT_REF_UUID", "CROAT_REF_PARENT_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_ORG_TREE"
    ADD CONSTRAINT "CROAT_UUID" UNIQUE ("CROAT_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_OPERATOR_CONFIG"
    ADD CONSTRAINT "CROFG_UUID" UNIQUE ("CROFG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_ORGANIZATION"
    ADD CONSTRAINT "CRORG_UUID" UNIQUE ("CRORG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_UAMS_APP"
    ADD CONSTRAINT "CUAPP_UUID" UNIQUE ("CUAPP_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_UAMS_OUTPUT_GRANT"
    ADD CONSTRAINT "CUOGRT_UUID" UNIQUE ("CUOGRT_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_DASVC_LOG"
    ADD CONSTRAINT "DASLG_UUID" UNIQUE ("DASLG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_SMS_LIST"
    ADD CONSTRAINT "LIST_UUID" UNIQUE ("LIST_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_MACHINE"
    ADD CONSTRAINT "MAC_UUID" UNIQUE ("MAC_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_OAUTH_CLIENT"
    ADD CONSTRAINT "OATCT_CLTID" UNIQUE ("OATCT_CLTID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_OAUTH_CLIENT"
    ADD CONSTRAINT "OATCT_UUID" UNIQUE ("OATCT_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_OAUTH_LOG"
    ADD CONSTRAINT "OATLG_UUID" UNIQUE ("OATLG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_SMS_REPLY"
    ADD CONSTRAINT "REPLY_UUID" UNIQUE ("REPLY_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_ACCOUNT_RELATION"
    ADD CONSTRAINT "SAR_UUID" UNIQUE ("SAR_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_SEND_AUTH"
    ADD CONSTRAINT "SAU_UUID" UNIQUE ("SAU_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_SEGMENT"
    ADD CONSTRAINT "SEG_UUID" UNIQUE ("SEG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_SMS_SEND"
    ADD CONSTRAINT "SEND_UUID" UNIQUE ("SEND_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_SESSION_LOG"
    ADD CONSTRAINT "SESSLG_UUID" UNIQUE ("SESSLG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_OP_FORWARD"
    ADD CONSTRAINT "SOF_UNID" UNIQUE ("SOF_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."S_SCTION"
    ADD CONSTRAINT "SSC_UUID" UNIQUE ("SSC_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_OAUTH_TICKET"
    ADD CONSTRAINT "TCKT_UUID" UNIQUE ("TCKT_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_INST_CONFIG"
    ADD CONSTRAINT "WFCFG_UUID" UNIQUE ("WFCFG_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_CMD"
    ADD CONSTRAINT "WFCMD_UUID" UNIQUE ("WFCMD_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_FLOW"
    ADD CONSTRAINT "WFFLW_CODE" UNIQUE ("WFFLW_CODE", "WFFLW_VERSION");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_FLOW"
    ADD CONSTRAINT "WFFLW_UUID" UNIQUE ("WFFLW_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_RESULT"
    ADD CONSTRAINT "WFHDR_UUID" UNIQUE ("WFHDR_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_RESULT"
    ADD CONSTRAINT "WFHDR_WFNDS_UUID" UNIQUE ("WFHDR_WFNDS_UUID", "WFHDR_OWNER_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_INSTANCE"
    ADD CONSTRAINT "WFINST_UUID" UNIQUE ("WFINST_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_NODE"
    ADD CONSTRAINT "WFNDE_UUID" UNIQUE ("WFNDE_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_STATUS"
    ADD CONSTRAINT "WFNDS_UUID" UNIQUE ("WFNDS_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_PROCESS"
    ADD CONSTRAINT "WFPRO_UUID" UNIQUE ("WFPRO_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_ROUTER"
    ADD CONSTRAINT "WFRTE_UUID" UNIQUE ("WFRTE_UUID");
ALTER TABLE "RISEN_JHSDYS_SMS_RSERVER"."CORE_WKFLW_FILE"
    ADD CONSTRAINT "WKFILE_UUID" UNIQUE ("WKFILE_UUID");
