ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_ADDRESS_BOOK"
    ADD CONSTRAINT "AK_KEY_2_CORE_ADD" UNIQUE ("CRARB_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_APP"
    ADD CONSTRAINT "AK_KEY_2_CORE_APP" UNIQUE ("CRAPP_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_ATTACHMENT"
    ADD CONSTRAINT "AK_KEY_2_CORE_ATT" UNIQUE ("CRATM_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_BUSINESS_ATTATCHMENT"
    ADD CONSTRAINT "AK_KEY_2_CORE_BUS" UNIQUE ("CRBSN_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_COLUMN_METADATA"
    ADD CONSTRAINT "AK_KEY_2_CORE_COL" UNIQUE ("CRCMD_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_DATABASE_METADATA"
    ADD CONSTRAINT "AK_KEY_2_CORE_DAT" UNIQUE ("CRDBM_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_DICT"
    ADD CONSTRAINT "AK_KEY_2_CORE_DIC" UNIQUE ("CRDCT_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_FUNCTION"
    ADD CONSTRAINT "AK_KEY_2_CORE_FUN" UNIQUE ("CRFNT_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_LOG"
    ADD CONSTRAINT "AK_KEY_2_CORE_LOG" UNIQUE ("CRLOG_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_MESSAGE_POOL"
    ADD CONSTRAINT "AK_KEY_2_CORE_MES" UNIQUE ("CRMGP_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_MESSAGE_HISTORY"
    ADD CONSTRAINT "AK_KEY_2_CORE_MES_H" UNIQUE ("CRMGP_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_ORG_APP"
    ADD CONSTRAINT "AK_KEY_2_CORE_OMA" UNIQUE ("CROMA_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_OUTER_APP"
    ADD CONSTRAINT "AK_KEY_2_CORE_OUT" UNIQUE ("CROTA_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_PORTAL_CFG"
    ADD CONSTRAINT "AK_KEY_2_CORE_POR" UNIQUE ("CRPTC_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_ROLE"
    ADD CONSTRAINT "AK_KEY_2_CORE_ROL" UNIQUE ("CRROL_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_SYNC_REGISTER"
    ADD CONSTRAINT "AK_KEY_2_CORE_SYN" UNIQUE ("CRSRG_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_TABLE_METADATA"
    ADD CONSTRAINT "AK_KEY_2_CORE_TAB" UNIQUE ("CRTMD_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_TEMPLATE"
    ADD CONSTRAINT "AK_KEY_2_CORE_TEM" UNIQUE ("CRTPL_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_TIMER_TASK"
    ADD CONSTRAINT "AK_KEY_2_CORE_TIM" UNIQUE ("CRTTK_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_TEST_EMIX"
    ADD CONSTRAINT "AK_TEST_EMIX" UNIQUE ("RSEMIX_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."OA_SWITCH_FORMATCONFIG"
    ADD CONSTRAINT "IDX_OSFC_UUID" UNIQUE ("OASFC_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."OA_SWITCH_TARGETCONFIG"
    ADD CONSTRAINT "IDX_OSTC_UUID" UNIQUE ("OASTC_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."OA_INFOREPORT"
    ADD CONSTRAINT "PK_OAIRUUID" UNIQUE ("OAIR_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."OA_LOGIN_LOG"
    ADD CONSTRAINT "PK_PALL_UUID" UNIQUE ("OALL_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."TYPT_ACC_SMEXTEND"
    ADD CONSTRAINT "PU_SM_TTUUID" UNIQUE ("TT_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."TYPT_ORG_SMEXTEND"
    ADD CONSTRAINT "PU_SM_UUID" UNIQUE ("TTORG_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."TYPT_ACC_TTEXTEND"
    ADD CONSTRAINT "PU_TTUUID" UNIQUE ("TT_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."CORE_ACCOUNT_COPY1"
    ADD CONSTRAINT "SYS_C00279873" UNIQUE ("CRACT_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."TYPT_ORG_TTEXTEND"
    ADD CONSTRAINT "TT_PU_UUID" UNIQUE ("TTORG_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."OA_EMAIL"
    ADD CONSTRAINT "UK_OAEMUUID" UNIQUE ("OAEM_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."OA_MEETING_APPLY_LOG"
    ADD CONSTRAINT "UK_OAMALUUID" UNIQUE ("OAMAL_UUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."OA_PENDING_MESSAGE"
    ADD CONSTRAINT "UK_OAPMITEMUUID" UNIQUE ("OAPM_ITEMUUID");
ALTER TABLE "RISEN_JHSDYS_XXBS"."WF_MESSAGE"
    ADD CONSTRAINT "UK_WFMESSAGEUUID" UNIQUE ("WFMESSAGE_UUID");
